# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac17a70a56f48a4c1d89cb22f7a29a535c8a139fd182a8dd3a524e7f249555a0888850b17832ed5bb8fab167134aa6fe38c700eec0bc0ba60af9e15dc4991e65

test:
  secret_key_base: adc78354fdbb81e442904f8cd648efa15c14b57c87caff461b7d260fd89aa960deb2e813df44560567604b987a984e29c66e285a200a52aae1f61a5628ecab18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
